package:
  name: lua
  version: 5.3.1

source:
  fn: lua-5.3.1.tar.gz
  url: http://www.lua.org/ftp/lua-5.3.1.tar.gz

build:
  number: 0
  binary_relocation: true

about:
  home: http://www.lua.org/
  license: MIT
  summary:  Lua is a powerful, fast, lightweight, embeddable scripting language.
