package:
  name: vera++
  version: 1.3.0

source:
  fn: vera++-1.3.0.tar.gz
  url: https://bitbucket.org/verateam/vera/downloads/vera++-1.3.0.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - cmake
    - boost
    - tcl
    - lua
    - python 2.7*
  run:
    - boost
    - tcl
    - lua
    - python 2.7*

test:
  commands:
    - vera++ --help

about:
  home: https://bitbucket.org/verateam/vera/wiki/Home
  license: Boost Software License
