package:
  name: buildbot-slave
  version: 0.8.12

source:
  fn: v0.8.12.tar.gz
  url: https://github.com/buildbot/buildbot/archive/v0.8.12.tar.gz

build:
  number: 0
  binary_relocation: true

requirements:
  build:
    - pip
    - python 2.7*
    - twisted >=8.0.0
  run:
    - python 2.7*
    - twisted >=8.0.0

test:
  commands:
    - buildslave --help

about:
  home: http://buildbot.net/
  license: GPL2
